id: PCC0BDDB4
initial_creation_type: input
source_metadata:
  title: Mipham Rinpoche Series
  language: en
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    8436532dcf60434f9cf922fdd8b72d19:
      title: Advice for Beginners
      parent: Advice
    1de5a1ade09646598f4aeac167655c7f:
      title: Advice to Jigme Tenpe Nyima
      parent: Advice
    23209388de3349439306074198adb2e9:
      title: Essence of the 84000 Approaches to the Dharma
      parent: Advice
    7d7bd2360e5c4e6abecfbd157591c056:
      title: How to Cultivate Concentration
      parent: Advice
    0b054a98b1b44a4ea3fd2e0550c8f847:
      title: Profound Instruction on Śamatha
      parent: Advice
    92f1dfca92324cf3b0fa969365371503:
      title: Satirical Advice for the Four Schools
      parent: Advice
    4b6a28eff18b4440826d162c25f89f02:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    9a25d3e5c2f044249d751df234741eb9:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    d635460c5db14b11a879e87e61061fdb:
      title: The Perfect Equality of the Dharmadhātu
      parent: Advice
    2c4fe8357d5d484890815f9e5357c8b5:
      title: A Brief Prayer for Summoning Prosperity
      parent: Aspiration Prayers
    acc09edce26948b8b25cd8dae90dffb2:
      title: Aspiration for the Four Activities
      parent: Aspiration Prayers
    1f422768381e485a8bcca53e4361dbcb:
      title: Light Offering Prayer
      parent: Aspiration Prayers
    82ca703c2a834d3c856db003e9b9bbea:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers
    6b3b362b3e5a4735bd54bb49a9dc80b6:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Aspiration Prayers
    d6f6dc14da4e4ba7b76379b88b0906e0:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
    da399311eec24750beb272a2ba934d6b:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Aspiration Prayers
    25e2626b06804579b5c76a4c65b66393:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    51362c247fde463ca4cc255173fb6d5b:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Averting Obstacles
    5b719b07d355426ab3a1f69af4a71c6e:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      parent: Benedictory Verses
    b83a687c3dcb4f998e76c8a586816740:
      title: Benedictory Verses for White Lotus
      parent: Benedictory Verses
    aa1773ad1ab54e879700204972c011c2:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Buddhist Philosophy
    2b9a771d8dd8469aa0699a0fa6ea40e6:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
    264b2db3595f45008f208178de954cb3:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Buddhist Philosophy
    8163d9dcf977416b9209e864436f6ed7:
      title: Profound Instruction on the View of the Middle Way
      parent: Buddhist Philosophy
    efd68a0c88314295aa1a1b5fb8fa5721:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Buddhist Philosophy
    a5d34c3211114794bb4ca22e7aa4b792:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Buddhist Philosophy
    5c9a7542690540e49c806a774cb55936:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Buddhist Philosophy
    39fd917a39004bbc92f236d4df71d932:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Buddhist Philosophy
    3546b8a03eaf48e7b0c61f18281083f7:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    05009eb055904e8897c040af588c3347:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Dharma Protectors
    19e29989beb84da3843ca1ce94bccc8d:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Dharma Protectors
    750173aa9705480fa14a4b747920c760:
      title: Brief Offering Prayer to Za Rāhula
      parent: Dharma Protectors
    f2e5fb7553a5467a9bb3ed7532f04cbd:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Dharma Protectors
    8cc8f18faee344dca4d9bc35405b6d7b:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Dharma Protectors
    ea0e16b93104439b89c142e0c1823f41:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Dzogchen
    27e1e4a11f5746fa9000b3e341ebe273:
      title: Pith Instruction on the Three Crucial Statements
      parent: Dzogchen
    fdc63cf1e362411c91f53e5af2630f3e:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    341f5c23912340f28921eedda1842b60:
      title: The Essence of Mind
      parent: Dzogchen
    bef1a0c7656e4264ab1ee1bc64565d3d:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Dzogchen
    33a3afe809a8478f9e6be2ba226a6d7d:
      title: The Key Points of Trekchö
      parent: Dzogchen
    fe5f6abd626540498def41f8c177d756:
      title: The Nature of Mind
      parent: Dzogchen
    eadbb73ed6d046b881b5762e7b46db30:
      title: Brief Gesar Windhorse Invocation
      parent: Gesar
    78a0c9b98db64eb8a8c76946b03efe2e:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    dbb34397056743748cade99ec1b6a0a2:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Gesar
    af2681b52b334c1394f884d4273afd9e:
      title: Prayer to Gesar
      parent: Gesar
    98333b12963a4943a265f75171ea153c:
      title: Short Windhorse Prayer to Gesar
      parent: Gesar
    db47d6c9649146d49835339ad03fa026:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Gesar
    ca6dfac21c6941f6bb61eab8fc2aac48:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Gesar
    8db2a9e2bf0f4e8aa3ff4be3847c5ec2:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Gesar
    643d7844360f46f695d8caefc1c052ee:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Gesar
    4871ddc890354921912a4b20ca270359:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    3a0ab47583844d3ea97574f639d47954:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    a404e9cfed21445f8c0ff0000e70f62f:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Guru Yoga
    33f296ad136d4bdebd40f820132ba552:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Guru Yoga
    a1e35a44c69848e0b28a81e36c9798c5:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    49917b706d3d4d0cbcd236375c8a9182:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    0594ab87b2da474fb1dae64f72871860:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Guru Yoga
    8a6599f63a7847d6951a3b4f22f381cc:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    16fab85f6e7846f3b1ee40b6e025f53c:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    cec348669e794834a06c2dab7e2260a8:
      title: Short Torma Offering to Kurukullā
      parent: Kurukullā
    81c9be7e34da41feb24e450386d3d4b6:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    566b79b4276d41fda8cc177b68bcc864:
      title: Brief Dzogchen Lineage Prayer
      parent: Lineage Prayers
    f9769e69102243e482d9368b1e2a614f:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    d50caba843494c6fa5f12334b7071d89:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    912244f08f59486bacf3f055d8de5ad2:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Longevity
    fa795f34530c44deb0954c885b81d208:
      title: Brief Windhorse Invocation
      parent: Lungta
    e8360a5f2d0a40f1b0eb4caef84b85fb:
      title: Daily Lungta Recitation
      parent: Lungta
    b4f7ec9480e44014a5a4a015e3458584:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Lungta
    89c25746a6494296a61f4aa3978d03a0:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    7e1c758ffdd241cb9405936323517e64:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    06265d33885e4450ab732ce94f948384:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Offering
    d11e0144ba894a12b02599af9eac2aa4:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    5f52ef5168a34aca9c859286084c753c:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Praise
    916fbefd1cd9478b8071b03e8c469c84:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    23da7cd52a474fce91e16c13dd553212:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    070b172a7c6b4000ab9f83414aef5f33:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Prayers
    c4369db91c2c424fb2271d3ce3073dc5:
      title: Prayer to Akṣobhya
      parent: Prayers
    d3917906e3fe425c8224144826fdf798:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
    9b5637b22b0e4c9e87038fafa3839101:
      title: Three Prayers from the Earth Pig Year
      parent: Prayers
    d3098fe0b9524b82b0f687931ee11809:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    a20f66df9fe64f35b4b60dc4d9797848:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Prayers to Guru Rinpoche
    4179fed75514443982a13fe3ce4b444d:
      title: Recollecting the Deeds of The Tenth Days
      parent: Prayers to Guru Rinpoche
    4447d8f08f6e4f8b9dfada3972c87bde:
      title: The Prayer which is the Source of All True Realization
      parent: Prayers to Guru Rinpoche
    e38fe5de10bf423691dd6c78d0e6eed6:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Prayers to Mañjuśrī
    897ecaa840ae49ab8d4736c6979fcc5a:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Prayers to Mañjuśrī
    fd036d4f9675475fb0fb571da2d87165:
      title: In Praise of the Protector Mañjughoṣa
      parent: Prayers to Mañjuśrī
    9ffb56e1a0e240768b02a98c0da85975:
      title: Prayer to Mañjuśrī
      parent: Prayers to Mañjuśrī
    b0dd6c95c4a047f8b0f108aa934cee75:
      title: Prayer to the Sovereign of Dharma and Retinue
      parent: Prayers to Śākyamuni
    0946859280124d78a79fb3ebef985213:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
    a9761336e50d4351a4b5f3d56421fe84:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: Preliminary Practice
    9ac7b4988d6842aaa24ce1378a9716cc:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    64439d32e43048f68e773cc7c3f01ce2:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    e36f18e56842416083f0cc6944ecc4d5:
      title: A Sādhana of Sitātapatrā
      parent: Sādhanas
    ae4258c895f74d2f8c77b34781cc9733:
      title: A Sādhana of White Sarasvatī
      parent: Sādhanas
    77c41e08438e4bacb6d0ffeec2e30f1d:
      title: Acala Sādhana
      parent: Sādhanas
    8b7ee590c17f463bb2d4a69f56cde5c7:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
    e3802a83a16245cc94cd1308c2852e0c:
      title: Sādhana of Mārīcī
      parent: Sādhanas
    a73a61211d314ec98c9008252220112c:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    901ea485efd8487eb5b421b72e578548:
      title: Brief Sang Offering
      parent: Sang Offering
    ef0804c4749549458c322728b58c954c:
      title: Brief Sang Offering to Purify Contamination
      parent: Sang Offering
    39315c5596cf42c1a4db017f2e23d9d1:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Saving Lives
    7c20dc66f1564d5da0ea8732a8f347e9:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    e3f2520caa6342839a4b2a1dd4efda52:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    64321bb0a6b04373809f138581f0885a:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Tārā
    cde0fe173f6e4dbdba37a91935ef2419:
      title: Outline of the Ten Royal Sūtras
      parent: Topical Outlines
    d2542ba4139c4a398404ca84cafec9a0:
      title: Concise Tsok Feast
      parent: Tsok
    b1da9fd2760e4bd3afa6f1dc2a9a4577:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Tsok
    4e4793045e0649dda3fc4a2d2a08e2b6:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Vajrasattva
created_at: '2022-03-01T00:57:12.435104'
last_modified_at: '2022-03-01T00:57:12.435112'
